In [2]:
import numpy as np

Exercício 1 — sum()


Crie um array com as vendas da semana [1500, 2300, 1800, 2700, 3100, 2500, 1900] e calcule o total vendido usando np.sum().

In [3]:
sales_week = np.array([1500, 2300, 1800, 2700, 3100, 2500, 1900])

In [4]:
print(f"Sales week: {np.sum(sales_week)} ")

Sales week: 15800 


Exercício 2 — mean()

Crie um array com as temperaturas da semana [28.5, 31.0, 29.3, 27.8, 30.1, 32.5, 26.9] e calcule a temperatura média usando np.mean(). Formate com 2 casas decimais.

In [12]:
temp_array = np.array([28.5, 31.0, 29.3, 47.8, 30.1, 32.5, 26.9])

In [13]:
media_temp = np.mean(temp_array)

In [14]:
print(f"A média das temperaturas foi: : {media_temp:.1f}")

A média das temperaturas foi: : 32.3


Exercício 3 — max() e min()

Crie um array com os preços [49.90, 129.90, 19.90, 89.90, 299.90, 9.90] e imprima o produto mais caro e o mais barato.

In [20]:
prices = np.array([49.90, 129.90, 99.90, 89.90, 299.90, 99.90])

In [21]:
print(f"highest price: {np.max(prices)}")
print(f"lowest price:  {np.min(prices)}")

highest price: 299.9
lowest price:  49.9


Exercício 4 — sort()

Crie um array com as notas [7.5, 9.0, 4.5, 8.0, 6.5, 3.0, 9.5] e ordene do menor para o maior.

In [24]:
array_student = np.array([7.5, 9.0 ,4.5, 8.0 ,6.5, 3.0, 9.5])

In [28]:
print(f"Ordenação: {np.sort(array_student)}")

Ordenação: [3.  4.5 6.5 7.5 8.  9.  9.5]


Exercício 5

Crie dois arrays:

quantity = [5, 3, 8, 2]
price = [50, 120, 30, 200]

Calcule o total da venda.

In [30]:
quantity = np.array([5, 3, 8, 2])

price = np.array([50, 120, 30, 200])

In [31]:
print(f"Valor da venda: {np.dot(quantity, price)}")

Valor da venda: 1250


Exercício 6

Crie um array com os salários [3500, 4200, 2800, 5100, 3900, 4700] e imprima:

Total da folha de pagamento

Salário médio

In [32]:
remuneration = np.array([3500, 4200, 2800, 5100, 3900, 4700])

In [33]:
total_remu = np.sum(remuneration)
print(f"Total Remuneração: {total_remu}")

Total Remuneração: 24200


In [38]:
print(f"Salário médio:  {np.mean(remuneration):.2f}")

Salário médio:  4033.33


Exercício 7

Crie um array com [88, 45, 72, 91, 63, 55, 78, 95, 40, 83], ordene e imprima somente os 3 maiores valores.

In [39]:
array_order = np.array([88, 45, 72, 91, 63, 55, 78, 95, 40, 83])

In [41]:
order_array = np.sort(array_order)
print(order_array)

[40 45 55 63 72 78 83 88 91 95]


In [77]:
print(order_array[-3::])

[88 91 95]


Exercício 8

Crie um array com as vendas diárias [320, 150, 480, 290, 510, 180, 440] e imprima:

Melhor dia de vendas


Pior dia de vendas


Média diária

In [117]:
diary_sale = np.array([320,450,480,390,510])

day_weeks = np.array(['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira'])

In [118]:
for i in range(len(diary_sale)):
    print(f"Dia: {day_weeks[i]} : {diary_sale[i]}")


Dia: Segunda-feira : 320
Dia: Terça-feira : 450
Dia: Quarta-feira : 480
Dia: Quinta-feira : 390
Dia: Sexta-feira : 510


In [119]:
#Melhor dia
better_day = np.argmax(diary_sale)
print(f"Melhor dia: {day_weeks[better_day]}\nValor do dia: {diary_sale[better_day]}")


Melhor dia: Sexta-feira
Valor do dia: 510


In [120]:
worst_day = np.argmin(diary_sale)
print(f"Pior dia: {day_weeks[worst_day]}\nTotal de venda: {diary_sale[worst_day]}")

Pior dia: Segunda-feira
Total de venda: 320


In [121]:
#Media diaria:
print(np.mean(diary_sale))

430.0


Crie um array com os preços [25.90, 49.90, 15.90, 89.90, 35.90, 199.90, 9.90]:

Ordene os preços

Imprima os 3 mais baratos

Calcule a média dos 3 mais baratos

In [132]:
array_prices = np.array([25.90, 49,90, 15.90, 89.90, 35.90, 199.90, 9.90])

In [133]:
order_prices = np.sort(array_prices)
print(order_prices)

[  9.9  15.9  25.9  35.9  49.   89.9  90.  199.9]


In [134]:
cheapest_prices = order_prices[:3]
print(cheapest_prices)

[ 9.9 15.9 25.9]


In [135]:
mean_prices = np.mean(cheapest_prices)
print(f"A média dos preços foi de: {mean_prices:.2f}")

A média dos preços foi de: 17.23


Exercício 10 — Desafio final

Crie três arrays:

products = ['Camiseta', 'Calça', 'Tênis', 'Boné']

sales = [150, 80, 60, 200]

price = [49.90, 129.90, 199.90, 39.90]

In [136]:
products = np.array(['Camiseta', 'Calça', 'Tênis', 'Boné'])

sales = np.array([150, 80, 60, 200])

price = np.array([49.90, 129.90, 199.90, 39.90])

In [197]:
for i in range(len(products)): 
    print(f"Produto {i + 1} : {products[i]}\n Peças vendidas:{sales[i]}\n Receita total: R${sales[i] * prices[i]}\n --------------------------")

Produto 1 : Camiseta
 Peças vendidas:150
 Receita total: R$7485.0
 --------------------------
Produto 2 : Calça
 Peças vendidas:80
 Receita total: R$10392.0
 --------------------------
Produto 3 : Tênis
 Peças vendidas:60
 Receita total: R$5994.0
 --------------------------
Produto 4 : Boné
 Peças vendidas:200
 Receita total: R$17980.0
 --------------------------


In [193]:
item_max = np.argmax(sales)

In [195]:
print(f"Item mais vendido: {products[item_max]}\nTotal geral: R${np.dot(sales,price):.2f}")

Item mais vendido: Boné
Total geral: R$37851.00
