Exercício 1


Crie um array com as vendas de janeiro [1200, 3400, 2100, 4500, 1800] e imprima o total, a média e o maior valor.

In [7]:
import numpy as np

In [8]:
sales_jan = np.array([1200, 3400, 2100, 4500, 1800])

In [9]:
#total
print(np.sum(sales_jan))

13000


In [10]:
#Média
print(np.mean(sales_jan))

2600.0


In [11]:
#Maior valor
print(np.max(sales_jan))

4500


Exercício 2

Crie um array com [55, 12, 89, 34, 67, 23, 91, 45], ordene e imprima os 3 menores e os 3 maiores.

In [12]:
array_numbers = np.array([55, 12, 89, 34, 67, 23, 91, 45])

In [13]:
#Ordernar
order_numbers = np.sort(array_numbers)
print(order_numbers)

[12 23 34 45 55 67 89 91]


In [14]:
#Menores
print(order_numbers[:3:])

[12 23 34]


In [15]:
#Maiores
print(order_numbers[-3::])

[67 89 91]


Exercício 3

Crie dois arrays:

products = ['Notebook', 'Mouse', 'Teclado', 'Monitor']
stock = [15, 200, 150, 30]

Use for para imprimir cada produto com seu estoque. No final imprima o produto com maior estoque e o com menor estoque.

In [16]:
products = np.array(['Notebook', 'Mouse', 'Teclado', 'Monitor'])

stock = np.array([15, 200,150, 30 ])

In [17]:
for i in range(len(products)):
    print(f"Produto: {products[i]}\nEstoque: {stock[i]}\n")

Produto: Notebook
Estoque: 15

Produto: Mouse
Estoque: 200

Produto: Teclado
Estoque: 150

Produto: Monitor
Estoque: 30



In [18]:
#Produito com mais venda:
sales_stock = np.argmax(stock)

In [19]:
#Maior venda
print(f"Produto: {products[sales_stock]}\nStock total: {stock[sales_stock]}")

Produto: Mouse
Stock total: 200


In [20]:
#Menor estoque
sales_stock_min = np.argmin(stock)

In [21]:
print(f"Produto: {products[sales_stock_min]}\nEstoque total: {stock[sales_stock_min]}")

Produto: Notebook
Estoque total: 15



Exercício 4

Crie um array com os números de 1 a 30 usando np.arange(). Pegue somente os múltiplos de 4, inverta e imprima o total usando np.sum().

In [22]:
array_number = np.arange(1, 31)

In [23]:
get_multple = array_number[3::4]

print(get_multple)

[ 4  8 12 16 20 24 28]


In [24]:
#Invertendo numeros
print(get_multple[::-1])



[28 24 20 16 12  8  4]


In [25]:
invet_numbers = get_multple[::-1]

In [26]:
print(np.sum(invet_numbers))

112


Exercício 5

Crie um array com as temperaturas [36.5, 37.2, 38.1, 36.8, 39.0, 37.5, 36.2] e imprima:

Temperatura mais alta

Temperatura mais baixa

Média das temperaturas

Temperaturas ordenadas

In [27]:
temperat = np.array([36.5, 17.2, 28.1, 26.8, 29.0, 27.5, 16.2])

day = np.array(['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sabado,' ,'Domingo'])

In [28]:
#Temperatura mais alta:
temp_high = np.argmax(temperat)
print(f"Dia mais quente: {day[temp_high]}\nTemperatura: {temperat[temp_high]}")

Dia mais quente: Segunda-feira
Temperatura: 36.5


In [29]:
#Temperatura mais baixa
temp_low = np.argmin(temperat)

In [30]:
print(f"Dia mais frio: {day[temp_low]}\nTemperatura: {temperat[temp_low]}")

Dia mais frio: Domingo
Temperatura: 16.2


In [31]:
#Média
print(f"Média das temperaturas: {np.mean(temperat):.2f}")

Média das temperaturas: 25.90


In [32]:
#Temperaturas ordenadas
print(np.sort(temperat))

[16.2 17.2 26.8 27.5 28.1 29.  36.5]


Exercício 6

Crie dois arrays:

hours = [8, 6, 10, 7, 9]
rate = [50, 75, 60, 80, 55]

Calcule o total pago a cada funcionário e o total geral da folha.

In [33]:
professional = np.array(['Victor', 'Cryscia', 'Fernanda', "Kaue", 'José'])

hours = np.array([8,6,10,7,9])

rate = np.array([50, 75,60, 80 ,55 ])

In [34]:
for i in range(len(hours)):
    print(f"Nome funcionario: {professional[i]}\nHoras trabalhas:{hours[i]}\nvalor total: {(hours[i] * rate[i])}\n")

Nome funcionario: Victor
Horas trabalhas:8
valor total: 400

Nome funcionario: Cryscia
Horas trabalhas:6
valor total: 450

Nome funcionario: Fernanda
Horas trabalhas:10
valor total: 600

Nome funcionario: Kaue
Horas trabalhas:7
valor total: 560

Nome funcionario: José
Horas trabalhas:9
valor total: 495



In [35]:
#Este acabei me confundindo. Irei altera-lo na proxima linha de comando.
#Seria calculado o total das horas trabalhadas, seguindo o calculo hours * rate. Quando sairia com todas as horas calculadas? 
total_rate = np.sum(rate)
print(f"Total geral: {total_rate}")

Total geral: 320


In [36]:
#Usando o .dto()
dot_geral = np.dot(hours, rate)

In [37]:
print(f"Total geral da folha: {dot_geral}")

Total geral da folha: 2505


Exercício 7

Crie um array com [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]:

Pegue os números entre 300 e 700 usando slice


Calcule a média desses números

Imprima o resultado

In [38]:
array_numbers = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])

In [39]:
get_numbers = array_numbers[2:7]

print(f"Numeros: {get_numbers}")

Numeros: [300 400 500 600 700]


In [40]:
#Calculando a média. 
get_mean = np.mean(get_numbers)
print(f"Média: {get_mean}")

Média: 500.0


Crie um array com as notas [6.5, 8.0, 4.5, 9.5, 7.0, 3.5, 8.5, 5.0] e use for para imprimir cada nota com sua situação e no final imprima:

Maior nota

Menor nota

Média da turma

In [44]:
grade_student = np.array([6.5, 8.0,  4.5, 9.5, 7.0 , 3.5, 8.5, 5.0])

student = np.array(['Victor', 'Cryscia', 'Kaue', 'Jose', 'Maria', 'Fernanda', 'Augusto', 'Gabriel'])

In [45]:
max_grade = np.argmax(grade_student)


In [50]:
print(f"Aluno com maior nota: {student[max_grade]}\nNota: {grade_student[max_grade]}")

Aluno com maior nota: Jose
Nota: 9.5


In [51]:
min_grade = np.argmin([grade_student])

In [52]:
print(f"Aluno com a menor nota: {student[min_grade]}\nNota: {grade_student[min_grade]}")

Aluno com a menor nota: Fernanda
Nota: 3.5


In [53]:
mean_class = np.mean(grade_student)


In [55]:
print(f"A média da turma é de: {mean_class:.2f}")

A média da turma é de: 6.56


In [95]:
for i in range(len(grade_student)):
    if grade_student[i] >=6 and grade_student[i] <= 10:
        print(f"Nome: {student[i]}\nNota: {grade_student[i]}\nSituação: Aprovado\n")
    elif grade_student[i] == 5.75 and grade_student[i] < 6:
        print(f"Nome: : {student[i]}\nNota: {grade_student[i]}\nSituação: Avaliação final.\n")
    elif grade_student[i] < 5.74:
        print(f"Nome: {student[i]}\nNota: {grade_student[i]}\nSituação: reprovado\n")

Nome: Victor
Nota: 6.5
Situação: Aprovado

Nome: Cryscia
Nota: 8.0
Situação: Aprovado

Nome: Kaue
Nota: 4.5
Situação: reprovado

Nome: Jose
Nota: 9.5
Situação: Aprovado

Nome: Maria
Nota: 7.0
Situação: Aprovado

Nome: Fernanda
Nota: 3.5
Situação: reprovado

Nome: Augusto
Nota: 8.5
Situação: Aprovado

Nome: Gabriel
Nota: 5.0
Situação: reprovado



Exercício 9

Crie um array com os números de 1 a 50 usando np.arange(). Sem usar for:

Pegue os números pares

Pegue somente os últimos 5

Multiplique por 3

Some tudo

In [105]:
array_numbers = np.arange(1, 51)

In [106]:
numbers_ = array_numbers[1::2]

In [107]:
print(numbers_)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [117]:
last_numbers = numbers_[-5::]
print(last_numbers)

[42 44 46 48 50]


In [118]:
multiple_numbers = (last_numbers * 3)
print(multiple_numbers)

[126 132 138 144 150]


In [119]:
sum_numbers = np.sum(multiple_numbers)

In [120]:
print(sum_numbers)

690
