In [3]:
import numpy as np

Exercício 1 — Indexação básica
Crie um array com ['Python', 'Java', 'C++', 'JavaScript', 'Go'] e imprima o primeiro e o último elemento.

In [16]:
#Creating index.
basic_index = ['Python', 'Java', 'C++', 'JavaScript', 'Go']
array_index = np.array(basic_index)

In [22]:
print(array_index[0])
print(array_index[-1])

Python
Go


Exercício 2 — Índice negativo
Crie um array com os números [10, 20, 30, 40, 50, 60, 70] e imprima o penúltimo elemento usando índice negativo.

In [24]:
indi_negative = np.array([10, 20, 30, 40, 50, 60, 70])

In [25]:
print(indi_negative[-2])

60


Exercício 3 — Slice básico

Crie um array com [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] e imprima somente os 5 primeiros elementos.

In [30]:
slice_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [32]:
print(slice_array[0: 5])

[1 2 3 4 5]


Exercício 4 — Slice com step

Com o mesmo array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], imprima somente os números ímpares usando step.

In [ ]:
step_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(step_array[::2])

[1 3 5 7 9]


Exercício 5 — Slice do meio

Crie um array com ['a', 'b', 'c', 'd', 'e', 'f', 'g'] e imprima somente os elementos do meio, excluindo o primeiro e o último.

In [35]:
array_elements = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g'])

In [57]:
#Mais elegante
print(array_elements[1: -1])

#Jeito correto, porem menos usado.
print(array_elements[1: 6])

['b' 'c' 'd' 'e' 'f']
['b' 'c' 'd' 'e' 'f']


Exercício 6 — Reverso

Crie um array com [1, 2, 3, 4, 5] e imprima ele ao contrário sem usar for.

In [40]:
array_reverse = np.array([1,2,3,4,5])

In [43]:
print(array_reverse[::-1])

[5 4 3 2 1]


Exercício 7 — Slice com índice negativo

Crie um array com [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] e imprima os últimos 3 elementos usando slice.

In [44]:
last_index = np.array([10,20,30,40,50,60,70,80,90,100])

In [47]:
print(last_index[7:10])

[ 80  90 100]


Exercício 8 — Step negativo

Crie um array com ['a', 'b', 'c', 'd', 'e', 'f'] e imprima de trás pra frente pulando de 2 em 2.

In [49]:
array_inverse = np.array(['a','b','c','d','e','f'])

In [64]:
print(array_inverse[::-2])

['f' 'd' 'b']


Exercício 9 — Combinando tudo

Crie um array com os números de 1 a 20 usando np.arange() e imprima somente os números pares de trás pra frente.

In [72]:
array_pars = np.arange(1, 21)

In [73]:
print(array_pars)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [74]:
print(array_pars[::-2])

[20 18 16 14 12 10  8  6  4  2]


Exercício 10 — Desafio criativo

Crie um array com as letras ['o', 'i', 'r', 'a', 'n', 'i', 'b'] e use slice pra formar uma palavra de trás pra frente.

In [75]:
array_mistery = np.array(['o', 'i','r','a','n','i','b'])

In [76]:
print(array_mistery[::-1])

['b' 'i' 'n' 'a' 'r' 'i' 'o']


Treinando mais arrays 


Exercício 1 — Criando e acessando

Crie um array com [100, 200, 300, 400, 500] e imprima o terceiro elemento usando indexação.


In [77]:
array_index = np.array([100,200,300,400,500])

In [78]:
print(array_index[2])

300


Exercício 2 — Índice negativo

Crie um array com ['banana', 'maçã', 'uva', 'laranja', 'manga'] e imprima os dois últimos elementos usando índice negativo.

In [79]:
array_negative = np.array(['banana','maça', 'uva', 'laranja','manga'])

In [80]:
print(array_negative[-2:])

['laranja' 'manga']


Exercício 3 — Slice

Crie um array com os números de 1 a 10 usando np.arange() e imprima somente do 3 ao 7.

In [81]:
array_numeric = np.arange(1,11)

In [82]:
print(array_numeric)

[ 1  2  3  4  5  6  7  8  9 10]


In [83]:
print(array_numeric[2:7])

[3 4 5 6 7]


Exercício 4 — Step

Crie um array com [0, 5, 10, 15, 20, 25, 30] e imprima de 2 em 2 elementos começando do início.

In [84]:
array_step = np.array([0,5,10,15,20,25,30])

In [85]:
print(array_step[::2])

[ 0 10 20 30]


Exercício 5 — Reverso parcial

Crie um array com ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] e imprima somente os 4 últimos elementos ao contrário.

In [87]:
array_inverse = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])

In [88]:
print(array_inverse[-4:][::-1])

['h' 'g' 'f' 'e']


Exercício 6 — Combinando slice e operação

Crie um array com [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], pegue os 5 primeiros e multiplique todos por 2.

In [89]:
array_calc = np.array([10,20,30,40,50,60,70,80,90,100])

In [90]:
print(array_calc[:5] * 2)

[ 20  40  60  80 100]


Exercício 7 — For + indexação

Crie um array com ['Python', 'NumPy', 'Pandas', 'Matplotlib', 'Sklearn'] e use for para imprimir cada elemento com sua posição. Exemplo: 0 - Python.

In [91]:
array_element = np.array(['Python', 'Numpy', 'Pandas', 'Matplotlib', 'Sklearn'])

In [92]:
for i in range(len(array_element)):
    print(f"Position {i} : {array_element[i]}")

Position 0 : Python
Position 1 : Numpy
Position 2 : Pandas
Position 3 : Matplotlib
Position 4 : Sklearn


Exercício extra — For + indexação

Crie um array com ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'] e use for para imprimir cada mês com seu número. Exemplo: Mês 1: Janeiro.

In [93]:
array_month = np.array(['Janeiro',
                         'Fevereiro',
                         'Março',
                         'Abril', 
                         'Maio', 
                         'Junho', 
                         'Julho',
                         'Agosto', 
                         'Setembro', 
                         'Outubro', 
                         'Novembro', 
                         'Dezembro'])

In [94]:
for array_position in range(len(array_month)):
    print(f" Month {array_position + 1}: {array_month[array_position]}")

 Month 1: Janeiro
 Month 2: Fevereiro
 Month 3: Março
 Month 4: Abril
 Month 5: Maio
 Month 6: Junho
 Month 7: Julho
 Month 8: Agosto
 Month 9: Setembro
 Month 10: Outubro
 Month 11: Novembro
 Month 12: Dezembro


Exercício extra 2 — For + indexação

Crie um array com [85, 92, 78, 95, 88, 73, 90] representando notas de alunos e use for para imprimir cada nota com sua situação. Exemplo:



Aluno 1: 85 - Aprovado


Aluno 2: 92 - Aprovado


Aluno 3: 78 - Reprovado

In [95]:
grade_student = np.array([10, 4, 10, 5.50, 5, 0, 5.99, 6])

In [96]:
for i in range(len(grade_student)):
    if grade_student[i] >= 6  and grade_student[i] <=10:
        print(f"Student {i + 1} : {grade_student[i]} \nSituation: Approved\n")
        
    elif grade_student[i] >5 and grade_student[i] <6:
        print(f"Student {i + 1} : {grade_student[i]}\nSituation: Second chance\n")
    
    else: 
        print(f"Student {i + 1} : {grade_student[i]}\nSituation: Disapproved\n")

Student 1 : 10.0 
Situation: Approved

Student 2 : 4.0
Situation: Disapproved

Student 3 : 10.0 
Situation: Approved

Student 4 : 5.5
Situation: Second chance

Student 5 : 5.0
Situation: Disapproved

Student 6 : 0.0
Situation: Disapproved

Student 7 : 5.99
Situation: Second chance

Student 8 : 6.0 
Situation: Approved



In [97]:
#Teste para o for -> Anotação feita no caderno e transferida para a linha de codigo.
exem_array = np.array(['Teste 1', 'Teste 2', 'Teste3 '])

In [99]:
for i in range(len(exem_array)):
    print( i +1 ,"--", exem_array[i])

1 -- Teste 1
2 -- Teste 2
3 -- Teste3 


Exercício 8 — Slice + operação

Crie um array com os números de 1 a 20 usando np.arange(), pegue somente os números pares e some todos usando np.sum().

In [100]:
list_number = np.arange(1, 21)

In [105]:
print((f"Even numbers: {list_number[1::2]}"))
print(f"Sum total: {np.sum(list_number[1::2])}")


Even numbers: [ 2  4  6  8 10 12 14 16 18 20]
Sum total: 110


Exercício 9 — Misturando tudo

Crie um array com [3, 6, 9, 12, 15, 18, 21, 24, 27, 30], inverta ele, pegue os 5 primeiros do array invertido e multiplique por 10.

In [106]:
array_invert = np.array([3, 6, 9, 12, 15, 18, 21, 24, 27, 30])

In [109]:
print("reverse: ", array_invert[::-1])
print(f"result multiply: {array_invert[::-1][:5] * 10}")

reverse:  [30 27 24 21 18 15 12  9  6  3]
result multiply: [300 270 240 210 180]


Exercício 10 — Desafio

Crie um array com os números de 1 a 100 usando np.arange(). Sem usar for:

1)Pegue somente os múltiplos de 5

2)Inverta

3)Some tudo com np.sum()

4)Imprima o resultado

In [112]:
array_numeric = np.arange(5, 101, 5)

In [113]:
print(array_numeric)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [114]:
print(array_numeric[::-1])

[100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25  20  15
  10   5]


In [115]:
print(f"Sum total: {np.sum(array_numeric[::-1])}")

Sum total: 1050
