Exercício 1 — Criando arrays : 
Crie um array NumPy com os números de 1 a 15 e imprima ele.

In [6]:
import numpy as np

In [7]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [10]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Podemos fazer esta forma tambem!

In [16]:
array = np.arange(1,16)

In [17]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Exercício 2 — dtype: 
Crie uma lista com os valores [10, "vinte", 30.5], transforme em array NumPy e imprima o dtype do array. O que aconteceu com os tipos?

In [ ]:
list_array = [10, "vinte", 30.5]

In [49]:
array_list = np.array(list_array)
print(array_list)

#imprimindo o dtype do array.
for elements in list:
    print(array_list.dtype)

['10' '11' '12.0']
<U32
<U32
<U32


O 'FOR' foi desnecessario. esta correto tambem, porem podemos fazer de uma forma mais pratica!

In [50]:
list_array = [10, '11', 12.0]

In [22]:
array = np.array(list_array)
print(list_array)
print(array.dtype)

[10, '11', 12.0]
<U32


Exercício 3 — for no array : 
Crie um array com 5 nomes de cidades brasileiras e use um for para imprimir o type() de cada elemento.

In [ ]:
#Criando a lista de 5 cidades.
city_list = ["São Paulo", "Rio de Janeiro", "Ceára", "Pernambuco", "Espirito Santo"]

In [28]:
#Usando o for para imprimir o type de cada cidade. 
for type_element in city_list: 
    print(type(type_element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Corrigindo algumas coisas

In [30]:
#Primeiro: Temos que transformar em array Numpy
city_array = np.array(city_list)

In [31]:
#Gerando o valores:
for element in city_array:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Exercício 4 — Operação em todos os elementos :
Crie um array com os preços [10.0, 25.5, 8.99, 100.0, 49.90] e aplique um desconto de 10% em todos de uma vez (sem usar for).

In [ ]:
#Criando os precos
prices = [10.0, 23.5, 8.99, 100.99, 49.90]

In [34]:
#Transformando em um array numpy
price_array = np.array(prices)

In [40]:
#Off (desconto)
print(f"off prices: {price_array - (price_array * 0.10)}")

off prices: [ 9.    21.15   8.091 90.891 44.91 ]


Exercicio 5 — Use range() para criar uma lista com os números pares de 0 a 20, depois transforme em array NumPy e imprima.

In [44]:
number_even = np.arange(0,22, 2)

array_numpy = np.array(number_even)

print(array_numpy)


[ 0  2  4  6  8 10 12 14 16 18 20]


In [57]:
#O exericio pedia range e não o ARANGE()
number_even = np.array(range(0, 22, 2))

print(number_even)

#---------------------------------------------------------------------------

#number_even = list(range(0, 22, 2))
#array_numpy = np.array(number_even)

#print(array_numpy)
#Error: 

#TypeError                                 Traceback (most recent call last)
#Cell In[56], line 2
#     1 #O exericio pedia range e não o ARANGE()
#----> 2 number_even = list(range(0, 22, 2))
#    3 array_numpy = np.array(number_even)
#      5 print(array_numpy)
#TypeError: 'list' object is not callable#

#lOGO ACIMA ESTA UM ERRO CLASSICO DE QUANDO O LIST JA ESTA DECLARADO, SENDO ASSIM NÃO PODEMOS USAR A FUNÇÃO LIST()

[ 0  2  4  6  8 10 12 14 16 18 20]


Exericio 6 --Crie uma lista normal [1,2,3,4,5] e tente fazer lista * 3. Depois faça o mesmo com um array NumPy. Imprima os dois resultados e explique a diferença com um comentário no código.

In [58]:
#Criando uma lista normal
normal_list = [1,2,3,4,5]

In [59]:
#Fazendo o calculo:
print(normal_list * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [60]:
#Criando o mesmo, porem com um array numpy. 
list_numpy = np.array(normal_list)

In [61]:
print(list_numpy * 3)

[ 3  6  9 12 15]


*Agora a pergunta*
  Qual a diferença entre o array normal e o array numpy? 
    A diferença esta clara! Quando usamos o um array normal e depois multiplicamos por 3, o python entende que, por causa das virgulas, ele repete novamente  todo o array. 
     
    Quando utilizamos o array numpy, ao inves de multiplicar o array, ele multiplica cada um elemento. 



Exericio 7 --Use np.arange() para criar um array que vai de 0 a 1 com passo de 0.1. Imprima o array e o dtype.

In [63]:
array = np.arange(0, 1, 0.1)

In [64]:
print(array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [65]:
print(array.dtype)

float64


Exercício 8 — Operações matemáticas: 
Crie um array com as temperaturas em Celsius [0, 20, 37, 100] e converta todas para Fahrenheit. A fórmula é: F = C * 9/5 + 32

In [67]:
temperature = np.array([0, 20, 37, 100])

In [69]:
#Convertendo em fahrenheit
fahrenTemp = (temperature * 9/5 + 32)

print(fahrenTemp)

[ 32.   68.   98.6 212. ]


Crie uma lista com [True, 1, 2.5, "texto"], transforme em array e responda com comentários no código:

    Qual foi o dtype resultante?
    Por que o NumPy escolheu esse tipo?

In [70]:
#Criando a lista.
create_list = [True, 1, 2.5, "texto teste"]

In [71]:
list_numpy = np.array(create_list)

In [72]:
print(list_numpy)
print(list_numpy.dtype)

['True' '1' '2.5' 'texto teste']
<U32


*Pergunta:*
Qual foi o dtype resultante?
R: O dtype resultante foi u32

Por que o NumPy escolheu esse tipo?
R: Pelo motivo de memoria. Se utilizarmos cada um de um tipo diferente, o numpy ira armazenar cada dado, sera utilizado muita memoria. 
Para acabar com isso, o numpy transformar todos em tipo STR_, pois ai irão ser elementos do mesmo tipo, e serão guardados todos com o mesmo tamanho fixo de memoria. 

Exercício 10 — Desafio:

Crie um array com os valores [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]. Sem usar for, calcule:

O dobro de cada valor
A soma de todos os valores do array resultante

In [73]:
#Criando o array
values = [1,2,3,4,5,6,7,8,9,10]

In [74]:
#Transformando o array em um array numpy
values_numpy = np.array(values)

In [76]:
#Calculando o dobro de cada elemento. 
double_value = (values_numpy * 2)
print(double_value)

[ 2  4  6  8 10 12 14 16 18 20]


In [78]:
#Soma de todos os valores:
sum_values = np.sum(double_value)

In [79]:
print(sum_values)

110
