In [3]:
import numpy as np

Exercício 1


Crie um array com os números de 1 a 50 usando np.arange(), pegue somente os múltiplos de 3 e imprima o primeiro e o último elemento usando indexação.

In [6]:
array_numeric = np.arange(3,50, 3)

In [30]:
print(array_numeric[2::3])

[ 9 18 27 36 45]


In [29]:
print(array_numeric[0])
print(array_numeric[-1])

3
48


Exercício 2

Crie um array com [15, 30, 45, 60, 75, 90, 105, 120], pegue os 4 primeiros, inverta e multiplique por 2.

In [31]:
array_list = np.array([15, 30, 45, 60, 75, 90, 105, 120])

In [32]:
#Pegando 4 primeiros numeros
get_numbers = array_list[:4]
print(get_numbers)

[15 30 45 60]


In [ ]:
#Invertendo a lista
print(get_numbers[::-1])

#Multiplicando os valores
print(get_numbers[::-1] * 2)


[60 45 30 15]
[120  90  60  30]


Exercício 3

Crie um array com ['React', 'Node', 'Python', 'Java', 'Go', 'Rust', 'C++'] e use for para imprimir cada linguagem com sua posição. Depois imprima somente as 3 últimas usando slice.

In [35]:
array_lang = np.array(['React', 'Node', 'Python', 'Java', 'Go', 'Rust', 'C++'])

In [39]:
for i in range(len(array_lang)):
    print(f"{i + 1}° ---- {array_lang[i]}")

1° ---- React
2° ---- Node
3° ---- Python
4° ---- Java
5° ---- Go
6° ---- Rust
7° ---- C++


In [46]:
print(array_lang[4::])

['Go' 'Rust' 'C++']


In [49]:
# Para deixar um pouco mais elegante, pode fazer desta maneira tambem:
print(array_lang[-3::])

['Go' 'Rust' 'C++']


Exercício 4

Crie um array com os números de 1 a 20 usando np.arange(). Sem usar for:

Pegue os números ímpares


Multiplique por 5

Some tudo com np.sum()

In [53]:
array_num = np.arange(1, 21)

In [55]:
#Array de 1 a 20
print(array_num)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [64]:
odd_numbers = array_num[::2]
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
#Multiplicando
multi_numbers = (odd_numbers * 5)
print(multi_numbers)

[15 30 45 60 75 90]


In [63]:
#Somando os numeros multiplicados
print(np.sum(multi_numbers))

315


Exercício 5

Crie um array com [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000], inverta, pegue de 2 em 2 e some tudo.

In [67]:
numeric_invert = np.array([100,200,300,400,500,600,700,800,900,1000])

In [72]:
#Invertendo os valores
array_invert = numeric_invert[::-1]
print(array_invert)

[1000  900  800  700  600  500  400  300  200  100]


In [76]:
#Pegando de 2 em 2
get_numbers = array_invert[::2]
print(get_numbers)

[1000  800  600  400  200]


In [77]:
np.sum(get_numbers)

3000