In [5]:
import numpy as np

In [18]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

In [10]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
list = [1, "dois", 3.0]
print(list)

[1, 'dois', 3.0]


In [12]:
print(type(list))

<class 'list'>


In [17]:
#Para verificar o tipo de cada elemento dentro da lista.
for element in list: 
    print(type(element))

<class 'int'>
<class 'str'>
<class 'float'>


In [ ]:
import numpy as np

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
list = [1, "dois", 3.0]
print(list)

[1, 'dois', 3.0]


In [ ]:
print(type(list))

<class 'list'>


In [ ]:
#Para verificar o tipo de cada elemento dentro da lista.
for element in list: 
    print(type(element))

<class 'int'>
<class 'str'>
<class 'float'>


In [ ]:
#Quando peguemos a lista com varios tipos de dados, o array() pega esses tipos de dados e transforma em um unico tipo, como no exemplo abaixo. 
#O termo mais usado é io String
array = np.array(list)

In [ ]:
print(array)

['1' 'dois' '3.0']


In [ ]:
#
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
for element in array: 
    print(type(element))

#O _ no numpy.str_ significa so para diferenciar do String do python.

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
#Temos outra forma, que é o tipo interno. 
#Unicode pode ter tanto caracteres e numeros quanto simbolos.  
print(array.dtype)

<U32


Operações Matemáticas

In [ ]:
#Não muito usado.
list = [1,2,3,4,5,6]

new_list = []

for number in list:
    new_list.append(number + 1)

print(new_list)

[2, 3, 4, 5, 6, 7]


In [ ]:
#Mais utilizado
new_array = np.array([1,2,3,4,5])
list_array = new_array * 10
print(list_array)

[10 20 30 40 50]


In [ ]:
#Quando peguemos a lista com varios tipos de dados, o array() pega esses tipos de dados e transforma em um unico tipo, como no exemplo abaixo. 
#O termo mais usado é io String
array = np.array(list)

In [20]:
print(array)

['1' 'dois' '3.0']


In [ ]:
#
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
for element in array: 
    print(type(element))

#O _ no numpy.str_ significa so para diferenciar do String do python.

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
#Temos outra forma, que é o tipo interno. 
#Unicode pode ter tanto caracteres e numeros quanto simbolos.  
print(array.dtype)

<U32


Operações Matemáticas

In [36]:
#Não muito usado.
list = [1,2,3,4,5,6]

new_list = []

for number in list:
    new_list.append(number + 1)

print(new_list)

[2, 3, 4, 5, 6, 7]


In [39]:
#Mais utilizado
new_array = np.array([1,2,3,4,5])
list_array = new_array * 10
print(list_array)

[10 20 30 40 50]
